### ISSUE TITLE
Tracking issue: v1-compatible CLI using Lib 2.0

### ISSUE THREAD

**Issue by passcod** [watchexec/watchexec#229]
- [x] Implement core functionality
- [x] Ignore loading
- [x] Option/flag parity
	- [x] `--changes-only` (compat) / `--print-events` (new)
	- [x] `--clear`, `-c`
	- [x] `--no-default-ignore`
	- [x] `--no-global-ignore` (new)
	- [x] `--no-environment`
	- [x] `--no-ignore` (compat) / `--no-project-ignore` (new)
	- [x] `--no-meta`
	- [x] `--no-process-group`
	- [x] `--no-shell`, `-n`
	- [x] `--no-vcs-ignore`
	- [x] `--postpone`, `-p`
	- [x] `--restart`, `-r`
	- [x] `--verbose`, `-v`
	- [x] `--watch-when-idle`, `-W` (compat)
	- [x] `--debounce`, `-d`
	- [x] `--exts`, `-e`
	- [x] `--filter`, `-f`
	- [x] `--ignore`, `-i`
	- [x] `--on-busy-update`
	- [x] `--watch`, `-w`
	- [x] `--force-poll`
	- [x] `--shell`
	- [x] `--signal`, `-s`
	- [x] `-k` (compat)
	- [x] `--once` (strict v1 compat, might not still be needed?)
	- [x] `@argfile`
	- [x] `--notify`
- [x] Add tagged filterer
	- [x] With `WATCHEXEC_FILTERER=tagged`:
		- [x] new option set appears instead of `-e`, `-f`, `-i`
		- [x] `--filter`, `-f` with tagged syntax
		- [x] `--filter-file`, `-F` taking a file of filters in tagged syntax (one per line)
		- [x] Filter files from env/global
		- [x] `--no-global-filters`
- [x] Check behaviour
	- [x] Check all options
	- [x] The [ignore file problem](https://twitter.com/passcod/status/1477098632167911426)
	- [x] Ignore .git if project is Git, etc
	- [x] file removal
- [x] Manpage updates
	- [x] `--notify`
	- [x] `--verbose` (multiple `-v`s)
	- [x] `--no-global-ignore`
	- [x] `--no-project-ignore`
	- [x] `--print-events`
	- [x] Updated env var behaviour
	- [x] All env vars read by watchexec
	- [x] Ignore files loaded (local and global)
- [x] ZSH Completion updates
	- [x] `--notify`
	- [x] multiple `-v`s
	- [x] `--no-global-ignore`
	- [x] `--no-project-ignore`
	- [x] `--print-events`

**Comment by passcod** [comment]
All done! Expect a release during the week.
